# ----------------------
# stampede configuration
#
# tasks that run when a PR is created or a new commit pushed
pullrequests:
  tasks:
    - id: pr-standards
      config:
        prMilestoneCheck: true
        prBodyCheck: true
    - id: swiftlint
      config:
        projectFolder: .
# tasks that run when a PR is edited
pullrequestedit:
  tasks:
    - id: pr-standards
      config:
        prMilestoneCheck: true
        prBodyCheck: true
# tasks that run when a release is created in GitHub
releases:
  published:
    tasks:
      - id: release-notes
